[package]
name = "pomodoro"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

indicatif = "0.17.2"
clap = { version = "4.0.29", features = ["derive"] }
